# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Filmsort < Formula
  desc "Film library manager."
  homepage "https://github.com/adam42389/filmsort"
  version "2.0.22"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/adam42389/filmsort/releases/download/v2.0.22/filmsort_Darwin_x86_64.tar.gz"
      sha256 "090714f0cd3bd739d89ace113581c17d95de688033d6122b12c9b487651f7b62"

      def install
        bin.install "filmsort"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/adam42389/filmsort/releases/download/v2.0.22/filmsort_Darwin_arm64.tar.gz"
      sha256 "0dd53707b44f1050368faf9ca546097bd77f359664d5b9d99aa668996c4d1225"

      def install
        bin.install "filmsort"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/adam42389/filmsort/releases/download/v2.0.22/filmsort_Linux_armv6.tar.gz"
      sha256 "02826846fbb77cc4452797cb1e033fbde016aaa0b75840a168c83aec8392bb78"

      def install
        bin.install "filmsort"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/adam42389/filmsort/releases/download/v2.0.22/filmsort_Linux_x86_64.tar.gz"
      sha256 "446f0e1bfa5486e437ebb7a4096bc406b67c64181e188ad4c2faded71e482f81"

      def install
        bin.install "filmsort"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/adam42389/filmsort/releases/download/v2.0.22/filmsort_Linux_arm64.tar.gz"
      sha256 "89e98eddc651caad521549734e7b92d9b30e211e7c014e0b9a84aaae1fcf3a64"

      def install
        bin.install "filmsort"
      end
    end
  end
end
