# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Filmsort < Formula
  desc "Film library manager."
  homepage "https://github.com/adam42389/filmsort"
  version "2.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/adam42389/filmsort/releases/download/v2.1.1/filmsort_Darwin_x86_64.tar.gz"
      sha256 "49d560e301fc35ec79d4d67c9574105c7f46e2070a1537529123ed506c62f8da"

      def install
        bin.install "filmsort"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/adam42389/filmsort/releases/download/v2.1.1/filmsort_Darwin_arm64.tar.gz"
      sha256 "962f57e7c6dd4ec3be40d5ab7faf1b7d44dc160aeca21de76b397a890fb958cd"

      def install
        bin.install "filmsort"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/adam42389/filmsort/releases/download/v2.1.1/filmsort_Linux_armv6.tar.gz"
      sha256 "0692f9114743fffef272a799feed7f38ded7901f921b37365e14dfad9eda8caf"

      def install
        bin.install "filmsort"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/adam42389/filmsort/releases/download/v2.1.1/filmsort_Linux_arm64.tar.gz"
      sha256 "03741b29bfdea3f0554322362334380eb7c21181b07d4e918fcce5ecc0bd6347"

      def install
        bin.install "filmsort"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/adam42389/filmsort/releases/download/v2.1.1/filmsort_Linux_x86_64.tar.gz"
      sha256 "e78439f8f944a5d57df66507830a97eadfb8e8ad54eb4772568a9e2b09d4b35f"

      def install
        bin.install "filmsort"
      end
    end
  end
end
